apiVersion: v1
kind: Service
metadata:
  name: {{ include "drf-example.fullname" . }}
  labels:
    {{- include "drf-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: http-static
      protocol: TCP
      name: http-static
  selector:
    {{- include "drf-example.selectorLabels" . | nindent 4 }}
